# Generated by Django 5.0.6 on 2024-12-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust',
            name='password',
            field=models.CharField(default='12345678', max_length=128),
        ),
    ]
